### ISSUE TITLE
Verify in continuous integration tests that the documentation compiles

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/recog#151]
A couple of times recently, a PR has been merged into master which broke the compilation of the documentation. If our continuous integration tests (for now, Travis) checked whether the documentation compiled properly, then we wouldn't have to worry about this happening.

**Comment by fingolfin** [comment]
Agreed! It shouldn't be all that hard either, somebody just needs to insert the equivalent of `gap makedoc.g` into the Travis scripts (with suitable options given to GAP to ensure that it exits with a non-zero exit code if there is an error, instead of getting stuck in a break loop).

**Comment by fingolfin** [comment]
Indeed, perhaps this should be the default for *all* packages (at least all that have a `makedoc.g` file), by adding such a thing to https://github.com/gap-system/pkg-ci-scripts (perhaps with an option to turn it off by setting a suitable env variable).

BTW, GAPDoc now has an option to turn off generating PDFs, which is quite handy for this, as it means that one doesn't need to install pdflatex in order to run `makedoc.g`. It's so far only in the GAPDoc repository, though, not yet in a release

**Comment by fingolfin** [comment]
I am working on this now in PR #152

**Comment by fingolfin** [comment]
Done in PR #152

**Comment by wilfwilson** [comment]
Thanks
