### ISSUE TITLE
Sporadic.tst fails sometimes

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/recog#56]
From a [travis test run](https://travis-ci.org/gap-packages/recog/jobs/508982818)
```
########> Diff in /home/travis/build/gap-packages/recog/gaproot/pkg/recog/tst/\
quick/Sporadic.tst:31
# Input is:
TestSporadic("HS");
# Expected output:
[ "HS" ]
# But found:
[ "HS.2" ]
########
########> Diff in /home/travis/build/gap-packages/recog/gaproot/pkg/recog/tst/\
quick/Sporadic.tst:33
# Input is:
TestSporadic("M24");
# Expected output:
[ "M24" ]
# But found:
[ "Co3" ]
```

**Comment by fingolfin** [comment]
So in general, many of our test files may fail if they are run again, because they depend on the exact state of the random number generator. But they should normally not fail on Travis, as we reset the RNG... but of course if you insert tests before other tests, that may break...

So one solution is to make sure the new .tst file is run last (which right now boils down to adjusting its name). Of course we could also use `START_TEST` / `STOP_TEST` in all .tst files, which resets the RNG seed, *but* I kinda like that one can read those .tst files multiple times to triggers issues (as we can then investigate those)... Hrmmm

**Comment by fingolfin** [comment]
This shouldn't be a problem at the moment anymore, at least I haven't seen it in quite some time.
