### ISSUE TITLE
Documentation: gap makedoc.g throws error when package is loaded automatically.

### ISSUE THREAD

**Issue by FriedrichRober** [gap-packages/recog#64]
If the package is loaded automatically by gap, one cannot run makedoc.g with gap.

```
Error, another version of package recog is already loaded at /home/friedrich/gap-4.10.1/lib/package.gi:1678 called from <function "SetPackagePath">( <arguments> )
 called from read-eval loop at regen_doc.g:3
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

**Comment by ssiccha** [comment]
I've seen that the Makefile uses `-A` to start gap. Is that the option to not load packages? If so, the `makedoc.g` could print a message to use `make doc` or start gap with `-A`.

**Comment by fingolfin** [comment]
This affects *every* package that uses AutoDoc. But it only really matters if you are (a) developing a package, and (b) if you have two "versions" of the package around, and both have the same version. I changed the version in git to `1.3.2dev` yesterday, which should take care of this.

**Comment by ssiccha** [comment]
Ah. So that should solve the most cases.

But for me the error is not thrown by the `AutoDoc` call but by the line
`SetPackagePath("recog", "./");` in `regen_doc.g`.
My situation is that I have the `1.3.2dev` version in a directory `PATH/pkg/recog/` where I declare PATH as an additional GAP root directory. That way for me the `1.3.2dev` version gets automatically loaded with GAP (unless I use the -A option). Thus `SetPackagePath` complains that `recog` is already loaded.

So instead I suggest to delete the `SetPackagePath` line in `regen_doc.g`. I updated PR #67 accordingly.

**Comment by fingolfin** [comment]
Ah, I see what you mean. But just deleting `SetPackagePath` is not acceptable, it is there for an important reason: For `regen_doc.g` to work correctly, it must be using the correct version of recog.

What could be done, though, is this: if recog is not loaded, use `SetPackagePath` to load the correct version. If it is loaded, inspect its package info record, and check its `InstallationPath` to verify that it refers to the correct directory.
